# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# THEME SPECIFIC CONFIGURATION
title: Medicus Pilsensis
email: medicuspilsensis@gmail.com
description: >- # this means to ignore newlines until "baseurl:" Spolek LFP
tagline: Spolek LFP
avatar: assets/img/logo.png

# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://medicuspilsensis.cz"# the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  mattiikk

# HEADER AND FOOTER TEXT
header_text: Medicus Pilsensis
header_feature_image: assets/img/page/header.jpg
footer_text: Copyright 2020

# BLOG
paginate: 5
paginate_path: "blog/page:2/"
excerpt: true
post_navigation: true

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name


# Build settings
theme: type-on-strap
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  
# Features
katex: true                                             # Enable if using math markup
google_analytics: UA-178698242-1                        # Tracking ID, e.g. "UA-000000-01"
cookie_consent: true                                   # To respect the usage of cookies
disqus_shortname:                                       # Your discus shortname for comments
layout_variables:                                       # Open the "_sass > base" folder, and open "_variables.scss"
footer_icons:                                           # In _data/social.yml
share_buttons:                                          # In _data/social.yml
authors:                                                # In _data/authors.yml
language:

# SEO
google_site_verification: OZRAsLyrYms3JTIOZ63rK-OBLr3MHlOYMUIlkC1CaqE


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
